name: flutter_graphql_jobs
description: A example of how to use a GraphQL client with bloc.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  # bloc state manager
  flutter_bloc: ^7.3.1
  graphql: ^5.0.0
  json_annotation: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  json_serializable: ^4.0.0
  lints: ^1.0.1

flutter:
  uses-material-design: true
